name: Release Pipeline

on:
  push:
    tags:
      - 'v0.1.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run Tests
        run: nextflow run tests/unit_tests.nf

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/artifact1
            path/to/artifact2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
